# Generated by Django 3.0.8 on 2020-08-28 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('isin', models.CharField(max_length=50)),
                ('current_price', models.FloatField()),
                ('buying_price', models.FloatField()),
                ('current_return', models.FloatField()),
                ('buying_return', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('bound_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Bound')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bound',
            name='account',
            field=models.ManyToManyField(to='assets.Account'),
        ),
    ]
