# Generated by Django 3.1 on 2021-01-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_moneymanagertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfer_id',
            field=models.CharField(blank=True, help_text='ID операции', max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('account_income', 'date_of_application', 'execution_date', 'type', 'sum', 'currency'), name='unique_transfer'),
        ),
    ]
