# Generated by Django 3.1 on 2020-09-13 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20200913_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpBound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('isin', models.CharField(max_length=50)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('assessed_return', models.FloatField(blank=True, null=True)),
                ('maturity_date', models.DateTimeField()),
                ('coupon_date_return', models.DateTimeField(blank=True, null=True)),
                ('coupon_price', models.FloatField(blank=True, null=True)),
                ('capitalization', models.IntegerField(blank=True, null=True)),
                ('coupon_duration', models.IntegerField(blank=True, null=True)),
                ('listing', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('demand_volume', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('tax_free', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CorpBoundTaxFree',
        ),
    ]
