# Generated by Django 3.1 on 2020-09-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20200913_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpbound',
            name='nkd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpbound',
            name='short_name',
            field=models.CharField(default=0, help_text='Сокращенное наименование', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='assessed_return',
            field=models.FloatField(blank=True, help_text='Доход оценочный в %', null=True),
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='capitalization',
            field=models.IntegerField(blank=True, help_text='Оборот', null=True),
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='coupon_date_return',
            field=models.DateTimeField(blank=True, help_text='Ближайшая дата выплаты купона', null=True),
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='coupon_duration',
            field=models.IntegerField(blank=True, help_text='Длительность купона', null=True),
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='coupon_price',
            field=models.FloatField(blank=True, help_text='Размер купона', null=True),
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='demand_volume',
            field=models.IntegerField(blank=True, help_text='Общий спрос', null=True),
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='duration',
            field=models.FloatField(blank=True, help_text='Дюрация', null=True),
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='last_price',
            field=models.FloatField(blank=True, help_text='Цена последней сделки', null=True),
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='listing',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], help_text='Листинг'),
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='maturity_date',
            field=models.DateTimeField(help_text='Дата погашения'),
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='name',
            field=models.CharField(help_text='Полное наименование', max_length=255),
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='tax_free',
            field=models.BooleanField(help_text='Свободна от уплаты налогов'),
        ),
    ]
