# Generated by Django 3.1 on 2021-02-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20210227_1635'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transfer',
            name='unique_transfer',
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('account_income', 'execution_date', 'type', 'sum', 'currency'), name='unique_transfer'),
        ),
    ]
