# Generated by Django 3.1 on 2020-10-04 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20200921_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buycloseprice', models.FloatField(help_text='Цена закрытия в дату покупки, в рублях')),
                ('buysum', models.FloatField(help_text='Сумма покупки')),
                ('cashflow', models.FloatField(help_text='Купоны/ дивиденды')),
                ('earnings', models.FloatField(help_text='Доход')),
                ('error', models.TextField()),
                ('from_date', models.DateField(verbose_name='Дата покупки')),
                ('secid', models.CharField(help_text='Инструмент', max_length=255)),
                ('sellcloseprice', models.FloatField(help_text='Цена закрытия в дату продажи, в рублях')),
                ('sellsum', models.FloatField(help_text='Сумма продажи')),
                ('till_date', models.DateField(verbose_name='Дата продажи')),
                ('volume', models.IntegerField(help_text='Количество бумаг')),
                ('yield_percent', models.FloatField(help_text='Внутр. ставка доходности')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
