# Generated by Django 3.1 on 2020-10-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='buycloseprice',
            field=models.FloatField(blank=True, help_text='Цена закрытия в дату покупки, в рублях', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='buysum',
            field=models.FloatField(blank=True, help_text='Сумма покупки', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cashflow',
            field=models.FloatField(blank=True, help_text='Купоны/ дивиденды', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='earnings',
            field=models.FloatField(blank=True, help_text='Доход', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='sellcloseprice',
            field=models.FloatField(blank=True, help_text='Цена закрытия в дату продажи, в рублях', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='sellsum',
            field=models.FloatField(blank=True, help_text='Сумма продажи', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='till_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='volume',
            field=models.IntegerField(blank=True, help_text='Количество бумаг', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='yield_percent',
            field=models.FloatField(blank=True, help_text='Внутр. ставка доходности', null=True),
        ),
    ]
