# Generated by Django 3.1 on 2021-04-23 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20210422_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.accountreport'),
        ),
    ]
