# Generated by Django 3.1 on 2020-10-04 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0008_auto_20201004_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='account',
            field=models.ForeignKey(default='af1dd10a-ab78-4e75-a535-28ea3d6087bc', on_delete=django.db.models.deletion.CASCADE, to='assets.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.FloatField(default=0, help_text='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, help_text='Описание', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='Номер счета или название', max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='bound_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='type',
            field=models.CharField(choices=[('Покупка', 'Покупка'), ('Продажа', 'Продажа')], max_length=50),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_application', models.DateTimeField(blank=True, help_text='Дата подачи поручения', null=True)),
                ('execution_date', models.DateTimeField(blank=True, help_text='Дата исполнения поручения', null=True)),
                ('type', models.CharField(choices=[('Ввод ДС', 'Ввод ДС'), ('Вывод ДС', 'Вывод ДС'), ('Списание комиссии', 'Списание комиссии'), ('Зачисление купона', 'Зачисление купона'), ('Зачисление суммы от погашения ЦБ', 'Зачисление суммы от погашения ЦБ'), ('Списание налогов', 'Списание налогов'), ('Зачисление дивидендов', 'Зачисление дивидендов')], help_text='Операция', max_length=50)),
                ('sum', models.FloatField(help_text='Сумма')),
                ('currency', models.CharField(help_text='Валюта', max_length=5)),
                ('charge_from', models.CharField(help_text='Списание с', max_length=50)),
                ('income_to', models.CharField(help_text='Зачисление на', max_length=50)),
                ('description', models.CharField(help_text='Содержание операции', max_length=255)),
                ('status', models.CharField(help_text='Статус', max_length=50)),
                ('account_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_charge', to='assets.account')),
                ('account_income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_income', to='assets.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
