# Generated by Django 3.1 on 2020-10-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20201004_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='charge_from',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='income_to',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='assets.account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='account_charge',
            field=models.ForeignKey(blank=True, help_text='Списание с', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_charge', to='assets.account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='account_income',
            field=models.ForeignKey(help_text='Зачисление на', on_delete=django.db.models.deletion.CASCADE, related_name='account_income', to='assets.account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='description',
            field=models.CharField(blank=True, help_text='Содержание операции', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='type',
            field=models.CharField(choices=[('Ввод ДС', 'Ввод ДС'), ('Вывод ДС', 'Вывод ДС'), ('Списание комиссии', 'Списание комиссии'), ('Зачисление купона', 'Зачисление купона'), ('Зачисление суммы от погашения ЦБ', 'Зачисление суммы от погашения ЦБ'), ('Списание налогов', 'Списание налогов'), ('Зачисление дивидендов', 'Зачисление дивидендов'), ('Перевод между счетами', 'Перевод между счетами')], help_text='Операция', max_length=50),
        ),
    ]
