# Generated by Django 3.1 on 2021-04-24 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_additionalinvestmentincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinvestmentincome',
            name='receipt_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 4, 24, 12, 3, 42, 925060)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additionalinvestmentincome',
            name='type',
            field=models.CharField(choices=[('Налоговый вычет', 'nalog')], max_length=50),
        ),
    ]
