# Generated by Django 3.1 on 2020-10-21 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20201006_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='bound_id',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='transaction_number',
        ),
        migrations.AddField(
            model_name='deal',
            name='amount',
            field=models.IntegerField(default=0, help_text='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='conclusion_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 20, 26, 42, 399534), help_text='Дата заключения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='isin',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='nkd',
            field=models.FloatField(default=0, help_text='НКД'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='number',
            field=models.IntegerField(default=0, help_text='Номер сделки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='settlement_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 20, 27, 28, 772661), help_text='Дата расчётов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='volume',
            field=models.FloatField(default=0, help_text='Объем сделки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='isin',
            field=models.CharField(help_text='ISIN', max_length=50),
        ),
        migrations.AlterField(
            model_name='corpbound',
            name='nkd',
            field=models.FloatField(help_text='НКД'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.FloatField(help_text='Цена'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='account',
            field=models.ForeignKey(help_text='Аккаунт', on_delete=django.db.models.deletion.CASCADE, related_name='account', to='assets.account'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='from_date',
            field=models.DateField(blank=True, help_text='Дата покупки', null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='till_date',
            field=models.DateField(blank=True, help_text='Дата продажи', null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='type',
            field=models.CharField(help_text='Операция', max_length=50),
        ),
    ]
