# Generated by Django 3.1 on 2021-05-06 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20210424_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinvestmentincome',
            name='receipt_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='IIS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_date', models.DateField()),
                ('sum', models.FloatField()),
                ('description', models.TextField()),
                ('remainder_limit', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
