# Generated by Django 3.1 on 2020-11-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20201021_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='account_id',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='deal',
            name='currency',
            field=models.CharField(help_text='Валюта', max_length=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='service_fee',
            field=models.FloatField(help_text='Комиссия'),
        ),
    ]
