# Generated by Django 3.1 on 2020-11-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20201129_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='isin',
            field=models.CharField(help_text='Код финансового инструмента', max_length=50),
        ),
        migrations.AlterField(
            model_name='deal',
            name='number',
            field=models.CharField(help_text='Номер сделки', max_length=50),
        ),
        migrations.AlterField(
            model_name='deal',
            name='type',
            field=models.CharField(choices=[('Покупка', 'Покупка'), ('Продажа', 'Продажа')], help_text='Операция', max_length=50),
        ),
    ]
