# Generated by Django 3.1 on 2021-05-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20210506_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IIS',
            new_name='IISIncome',
        ),
        migrations.AddConstraint(
            model_name='iisincome',
            constraint=models.UniqueConstraint(fields=('operation_date', 'sum', 'account'), name='unique_iis_income'),
        ),
    ]
