# Generated by Django 3.1 on 2021-05-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20210506_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='iisincome',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.accountreport'),
            preserve_default=False,
        ),
    ]
