# Generated by Django 3.1 on 2021-01-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20201129_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='deal',
            name='volume',
            field=models.FloatField(help_text='Объём сделки'),
        ),
    ]
