# Generated by Django 3.1 on 2021-01-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_auto_20210106_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='key',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
