# Generated by Django 3.1 on 2021-05-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_iisincome_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
