# Generated by Django 3.1 on 2021-05-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_delete_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreport',
            name='deals',
            field=models.JSONField(default=dict, help_text='Сделки купли/продажи ценных бумаг'),
        ),
    ]
