# Generated by Django 3.1 on 2021-01-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_template_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('asset_estimate', models.JSONField()),
                ('iis_income', models.JSONField()),
                ('portfolio', models.JSONField()),
                ('money_flow', models.JSONField()),
                ('tax', models.JSONField()),
                ('handbook', models.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.account')),
            ],
        ),
    ]
