# Generated by Django 3.1 on 2021-01-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_accountreport'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accountreport',
            constraint=models.UniqueConstraint(fields=('start_date', 'end_date', 'account_id'), name='unique_report'),
        ),
    ]
