# Generated by Django 3.1 on 2021-11-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_auto_20211102_1320'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transfer',
            name='unique_transfer',
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('account_income', 'execution_date', 'type', 'sum', 'currency', 'transfer_id'), name='unique_transfer'),
        ),
    ]
