# Generated by Django 3.1 on 2021-11-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_auto_20211102_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='price_rub',
            field=models.FloatField(default=0, help_text='Цена в рублях'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='sum_rub',
            field=models.FloatField(default=0, help_text='Сумма в рублях'),
            preserve_default=False,
        ),
    ]
