# Generated by Django 3.1 on 2022-01-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_auto_20220106_0035'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transfer',
            name='unique_transfer',
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('account_income', 'execution_date', 'description', 'type', 'sum', 'currency'), name='unique_transfer'),
        ),
    ]
