# Generated by Django 3.1 on 2021-01-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tinkoff_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
