# Generated by Django 3.1 on 2021-01-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210125_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='google_service_token',
            field=models.JSONField(default=dict),
        ),
    ]
