on:
  push:
    branches: 
      master

name: CD

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    environment: production

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/baa-service:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  aws:
    name: AWS
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_REGION: us-west-1
      TASK_DEFINITION: django-app:21
    steps:
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      -
        name: Force deployment
        run: |
            aws ecs update-service --cluster production-cluster --service production-service --force-new-deployment
